# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170322_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tittle',
            new_name='title',
        ),
    ]
