# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
