# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170320_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
