# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
