# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_olx', '0002_auto_20170404_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
